# Generated by Django 5.2 on 2025-04-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casalivingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='casalivingapp.amenitytag'),
        ),
        migrations.CreateModel(
            name='HouseAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='casalivingapp.house')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casalivingapp.amenitytag')),
            ],
        ),
    ]
