# Generated by Django 5.2 on 2025-05-14 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casalivingapp', '0003_houseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Full name of the reviewer', max_length=100)),
                ('reviewer_profile_pic', models.ImageField(blank=True, help_text='Optional profile picture of the reviewer', null=True, upload_to='reviewers/profile_pics/')),
                ('reviewer_location', models.CharField(blank=True, help_text='City or region of the reviewer (optional)', max_length=150)),
                ('description', models.TextField(help_text='Review content (max 1000 characters)', max_length=1000)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating between 1 (worst) and 5 (best)', validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating must not exceed 5.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
