# Generated by Django 5.2 on 2025-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casalivingapp', '0005_alter_house_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitytag',
            name='image',
            field=models.ImageField(default='', upload_to='amenities/'),
        ),
    ]
